#! /usr/bin/env ruby

# frozen_string_literal: true

def curl_install!(url)
  system "/bin/bash -c \"$(curl -fsSL #{url})\""
end

# Cribbed from
# https://raw.githubusercontent.com/thoughtbot/laptop/master/mac
#
# home_dir = File.expand_path('~')
# zshrc_path = home_dir / '.zshrc'
# def append_to_zshrc(line)
#   system("echo '#{line}' >> #{zshrc_path}")
# end

# create $HOME/.bin if it doesn't exist
# FileUtils.mkpath(home_dir / '.bin')

# create $HOME/.zshrc if it doesn't exist
# FileUtils.touch(zshrc_path)

# append $HOME/.bin to PATH (in .zshrc)
# append_to_zshrc 'export PATH=$HOME/.bin:$PATH'

# maybe update shell?

# install homebrew
homebrew_dir = if `uname -m`.chomp == "arm64"
  "/opt/homebrew"
else
  "/usr/local"
end
homebrew = File.join(homebrew_dir, "bin", "brew")

unless system("command -v brew > /dev/null")
  homebrew_installer_url = "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"

  # system "/bin/bash -c \"$(curl -fsSL #{homebrew_installer_url})\""
  curl_install! homebrew_installer_url

  # append_to_zshrc "eval \"$(#{homebrew} shellenv)\""
end

# system('brew uninstall --force brew-cask') if system('brew list | grep -Fq brew-cask')

# update homebrew
system "#{homebrew} update --force"

dotfiles_path = File.expand_path(File.join(File.dirname(__FILE__), ".."))
brewfile_path = File.join(dotfiles_path, ".Brewfile")

# install brews from .Brewfile
system "#{homebrew} bundle --file=#{brewfile_path}"

# config asdf, plugins
# append_to_zshrc("source $(#{homebrew} --prefix asdf)/asdf.sh")

# end cribbed script

# install OhMyZsh
curl_install! "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh"

# run rcup
system "env RCRC=#{File.join(dotfiles_path, "rcrc")} rcup"
